CRAW-206 | Robots txt ep
Hike-SEO/crawler-api-php pull request #8
Opened 2024-10-02 20:34 UTC by mante-hike

Not sure we need wait_until for this EP?

2024-10-03 15:06 UTC, Dan-Hike commented on app/Http/Controllers/Api/RobotsController.php
> +    public function __invoke(RobotsRequest $request): JsonResponse
In the both the v3 and v4 crawler projects, it looks like we handle redirects and follow them, presumably incase `/robots.txt` is redirected to the actual source. Probably worth replicating this in ours
https://github.com/Hike-SEO/CrawlerAPI/blob/main/src/robots/index.ts
https://github.com/kieranheadley/NodeCrawler/blob/master/functions/src/api/robots/getRobots.ts

2024-10-22 07:17 UTC, ross-hike requested changes
Nice one, just a small request plz mate

2024-10-22 07:17 UTC, ross-hike commented on app/Http/Controllers/Api/RobotsController.php
> +        ]);
Can we move this logic into a service please?

2024-10-22 07:17 UTC, ross-hike commented on tests/TestCase.php
> +    }
Noice

2024-11-14 11:52 UTC, mante-hike commented
@ross-hike nice one mate

2024-12-06 09:13 UTC, james-hike approved these changes

2024-12-08 17:56 UTC, ross-hike approved these changes

2024-12-21 11:42 UTC, merged